spring.application.name=Critiquehub

spring.datasource.url=jdbc:postgresql://localhost:5432/critiquehub
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

logging.level.root=INFO
logging.level.com.critiquehub=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.hibernate.SQL=INFO
spring.main.log-startup-info=false

app.async.core-pool-size=5
app.async.max-pool-size=15
app.async.queue-capacity=1000
app.async.thread-name-prefix=CritiqueHubAsync-

server.error.include-message=always
app.pagination.default-size=20
